import React from 'react';
import { render } from '@vhyxchart/core';

/** Props for {@link VhyxChartStatic}. */
export interface VhyxChartStaticProps {
  source?: string;
  children?: string;
  /** Emit a SMIL-animated SVG (plays without JavaScript). @default true */
  animated?: boolean;
  theme?: 'auto' | 'light' | 'dark';
  className?: string;
  style?: React.CSSProperties;
}

function dedent(text: string): string {
  const lines = text.replace(/^\n+|\s+$/g, '').split('\n');
  const indent = Math.min(...lines.filter((l) => l.trim()).map((l) => l.match(/^\s*/)?.[0].length ?? 0));
  return Number.isFinite(indent) && indent > 0 ? lines.map((l) => l.slice(indent)).join('\n') : lines.join('\n');
}

/**
 * Server-renderable diagram: no hooks, no client JavaScript. Works in React
 * Server Components, static exports and emails-to-HTML pipelines. With
 * `animated` (default) the SVG still moves, via SMIL.
 *
 * @example
 * // app/page.tsx (Server Component)
 * <VhyxChartStatic>{'flowchart LR\n A --> B'}</VhyxChartStatic>
 */
export function VhyxChartStatic({ source, children, animated = true, theme, className, style }: VhyxChartStaticProps): React.ReactElement {
  const { svg } = render(dedent(source ?? children ?? ''), { animated, ...(theme ? { theme } : {}) });
  // The SVG is generated by our own renderer from escaped text; no user HTML passes through.
  return <div className={className} style={style} data-vhyxchart-static="" dangerouslySetInnerHTML={{ __html: svg }} />;
}
